const products = [
  {
    id: "1",
    company: "Western Digital",
    name: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
    price: 6400,
    description:
      "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity. Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
    category: "HDD",
    image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    stars: 3.3,
    reviews: 203,
    stock: 10,
    featured: true,
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://images.pexels.com/photos/117729/pexels-photo-117729.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://5.imimg.com/data5/SELLER/Default/2020/8/YB/BF/GZ/111366528/2tb-wd-hard-disk-drive-1000x1000.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/81Pj2oJalML._SY450_.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "2",
    company: "SanDisk",
    name: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    price: 10900,
    description:
      "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    category: "SSD",
    image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    colors: ["#ff0000", "#000000", "#CDD0D0"],

    stars: 3.9,
    reviews: 470,
    stock: 12,
    featured: true,
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://img.merkandi.com/imgcache/resized/images/offer/2020/01/15//31440_0.jpeg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://sc04.alicdn.com/kf/H4036fb0ac3b8430fbef03f91a611be7ev.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/91ccihB9ixL._SY450_.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "3",
    company: "Silicon Power",
    name: "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    price: 10900,
    description:
      "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    category: "SSD",
    image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    colors: ["#ff0000", "#000000"],
    stars: 4.8,
    reviews: 319,
    stock: 5,
    featured: true,
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://www.onlyssd.com/wp-content/uploads/2022/10/Silicon-Power-P34A60-128GB-M.2-NVMe-Internal-SSD-SP128GBP34A60M28.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://www.primeabgb.com/wp-content/uploads/2019/02/Silicon-Power-256GB-NVMe-PCIe-Gen3-x4-M2-2280-SSD-SP256GBP34A80M28-1.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://5.imimg.com/data5/SELLER/Default/2022/5/EH/ZK/TT/3038212/sp-silicon-power-256gb-nvme-ssd-1000x1000.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "4",
    company: "Western Digital",
    name: "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    price: 11400,
    description:
      "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    category: "HDD",
    image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    stars: 4.8,
    reviews: 400,
    stock: 3,
    featured: true,
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/81py5g+it9L._SX679_.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://techmartunbox.com/wp-content/uploads/2019/08/western-digital-4tb-bluewd40ezrz-4147-600x600-600x600.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://gotoshop.online/image/cache/catalog/gotoshop/6-500x500.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "5",
    company: "Acer",
    name: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    price: 59900,
    description:
      "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    category: "Monitor",
    image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    colors: ["#ff0000", "#CDD0D0"],
    reviews: 250,
    stock: 14,
    featured: true,
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/81QpkIctqPL._AC_SL1500_.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/S/aplus-media/vc/b3973266-856e-424b-89c5-551989abe3e4._CR0,0,800,600_PT0_SX800__.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://www.lifewire.com/thmb/ZSq0cJSYUscFYaSBtWJ4jHai06E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Acer_SB220Q_Monitor_01LW4061369_6_Final_Horiz-cda109c444464d4384aee081cff3443b.jpg",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "6",
    company: "Samsung",
    name: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
    price: 99999,
    description:
      "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    category: "Monitor",
    image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    stars: 4.2,
    reviews: 140,
    stock: 15,
    featured: true,
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://image-us.samsung.com/SamsungUS/home/92621/C49HG90DMR_005_L-Perspective_Black.jpg?$product-details-jpg$",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://i.ytimg.com/vi/8dl6vHBiKWQ/maxresdefault.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://d3pbw4826yao71.cloudfront.net/010503/1501224952151_b_C49HG90_022_R-Perspective_Black.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "7",
    name: "iphone x",
    company: "apple",
    price: 600000,
    colors: ["#ff0000", "#000000", "#CDD0D0"],
    description:
      "The mobile is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "mobile",
    featured: true,
    stock: 5,
    reviews: 58,
    stars: 4.8,
    image:
      "https://static.digit.in/default/f0120c64aeeba5e126ae1711b0e2e64e7f6e40de.jpeg?tr=w-600",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://www.refurbished.store/cache/images/iphone-x-zwart_600x600_BGresize_16777215-tj.png",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://images.xtracover.com/APPLE_IPHONE-X-SPACE-GRAY-64-GB-3-GB-RAM-_N8M3V.JPG",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://i.guim.co.uk/img/media/91bc1db10420830da8e99ef7df362fbbbfd96dac/1_0_4277_2567/master/4277.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=327873b2b9c6af4135195848e7a574df",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "8",
    name: "samsung s20",
    company: "samsung",
    price: 500000,
    colors: ["#000", "#22D3EF"],
    description:
      "The mobile is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "mobile",
    shipping: true,
    stock: 10,
    reviews: 28,
    stars: 4.4,
    image: "https://m.media-amazon.com/images/I/81QVLzeVckL._SL1500_.jpg",
    image: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/81vDZyJQ-4L._SY879_.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://media.croma.com/image/upload/v1666992554/Croma%20Assets/Communication/Mobiles/Images/233768_9_g3bgvx.png",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://images.news18.com/ibnlive/uploads/2020/03/Samsung-Galaxy-S20-Plus-Main.png",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "9",
    name: "Dell Series",
    company: "dell",
    price: 702899,
    colors: ["#22D3EF", "#CDD0D0"],
    description:
      "The Laptop is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "laptop",
    stock: 12,
    reviews: 28,
    stars: 4.2,
    image:
      "https://i.dell.com/is/image/DellContent//content/dam/ss2/product-images/dell-client-products/notebooks/latitude-notebooks/14-3420/media-gallery/peripherals_laptop_latitude_3420nt_gallery_1.psd?fmt=pjpg&pscan=auto&scl=1&wid=3319&hei=2405&qlt=100,1&resMode=sharp2&size=3319,2405&chrss=full&imwidth=5000",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://cdn1.smartprix.com/rx-iQy0CRpy0-w1200-h1200/Qy0CRpy0.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://i.dell.com/is/image/DellContent//content/dam/ss2/product-images/dell-client-products/notebooks/latitude-notebooks/15-3520/media-gallery/peripherals_latop_latitude_3520_gallery_3.psd?fmt=pjpg&pscan=auto&scl=1&wid=3339&hei=2291&qlt=100,1&resMode=sharp2&size=3339,2291&chrss=full&imwidth=5000",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/61-yln4IXjL._SL1500_.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "10",
    name: "Mac Pc",
    company: "apple",
    price: 200999,
    colors: ["#000", "#CDD0D0"],
    description:
      "The Computer is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "computer",
    shipping: true,
    stock: 4,
    reviews: 28,
    stars: 2.8,
    images:
      "https://5.imimg.com/data5/SELLER/Default/2021/3/ZH/VL/BS/3770561/apple-all-in-one-computer-1000x1000.jpg",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://5.imimg.com/data5/HT/LA/VC/SELLER-12188422/apple-imac-desktop-computer-500x500.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://i.dell.com/is/image/DellContent//content/dam/ss2/product-images/dell-client-products/notebooks/latitude-notebooks/15-3520/media-gallery/peripherals_latop_latitude_3520_gallery_3.psd?fmt=pjpg&pscan=auto&scl=1&wid=3339&hei=2291&qlt=100,1&resMode=sharp2&size=3339,2291&chrss=full&imwidth=5000",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://images-cdn.ubuy.co.in/633b4fda4c68681cf45dffbb-apple-imac-21-5in-2-7ghz-core-i5.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },

  {
    id: "11",
    name: "Macbook Pro",
    company: "apple",
    price: 699999,
    colors: ["#000000", "#CDD0D0"],
    description:
      "The Laptop is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "laptop",
    shipping: true,
    stock: 6,
    reviews: 12,
    stars: 4.1,
    image:
      "https://i0.wp.com/maplestore.in/wp-content/uploads/2021/10/MacBook_Pro_16-in_Silver_PDP_Image_Position-1__en-IN-scaled.jpg?fit=2560%2C2560&ssl=1",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/mbp-spacegray-select-202206?wid=1280&hei=1190&fmt=jpeg&qlt=90&.v=1664497359481",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://photos5.appleinsider.com/gallery/45240-88149-The-new-MacBook-Pro-16-inch-xl.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://www.digitaltrends.com/wp-content/uploads/2021/11/macbook-pro-2021-01.jpg?p=1",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "12",
    name: "Asus gseries",
    company: "asus",
    price: 509999,
    colors: ["#CDD0D0", "#000"],
    description:
      "The laptop is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "laptop",
    shipping: true,
    stock: 6,
    reviews: 23,
    stars: 3.7,
    image: "https://m.media-amazon.com/images/I/71+d4hy0unL._SL1500_.jpg",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://www.asus.com/media/Odin/Websites/global/ProductLine/20200824120814.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/614tVoYYQrL._AC_SL1280_.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/81ahHX9wU1L._SL1500_.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "13",
    name: "accessories",
    price: 409999,
    company: "lenova",
    colors: ["#000", "#CDD0D0"],
    description:
      "The accessories is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "accessories",
    featured: true,
    shipping: true,
    stock: 6,
    reviews: 23,
    stars: 4.2,
    image:
      "https://images.pexels.com/photos/3178938/pexels-photo-3178938.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/71acOQV0elL._SL1500_.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/51ZJAaY8i2L._SL1000_.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://m.media-amazon.com/images/I/71sfODG+c+L._SL1500_.jpg",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "14",
    name: "Iwatch",
    price: 109999,
    company: "apple",
    colors: ["#000000"],
    description:
      "This watch is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "watch",
    shipping: true,
    stock: 6,
    reviews: 23,
    stars: 4.6,

    image:
      "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://static.toiimg.com/thumb/resizemode-4,msid-54128624,imgsize-200,width-1200/54128624.jpg",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://static.toiimg.com/thumb/resizemode-4,msid-54128624,imgsize-200,width-1200/54128624.jpg",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5ofcjvatzWkZhAB5DcpadHzmTgmwQ1jobUGaokpvihhgjKp5EhoVi4-GzcnailGCOiIQ&usqp=CAU",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
  {
    id: "thapaserialnok",
    name: "rolex premium",
    company: "rolex",
    price: 99999,
    colors: ["#000000", "#CDD0D0"],
    description:
      "This watch is compact with its 6.2-inch OLED screen and far lighter at 168g. It perfectly captures the design, looks, and feel of the expensive one. It comes with a snapdragon processor with a 5n chip in it. It has a 200mp camera in the rear 100mp in front perfect for selfie lovers. It also support HDR content means you can watch 4K content on it.",
    category: "watch",
    stock: 6,
    reviews: 60,
    stars: 4.8,
    image:
      "https://content.rolex.com/dam/2022-11/upright-bba-with-shadow/m126618lb-0002.png?impolicy=v6-upright&imwidth=270",
    images: [
      {
        id: "image1",
        width: 1080,
        height: 650,
        url: "https://content.rolex.com/dam/2022-11/upright-bba-with-shadow/m126284rbr-0049.png?impolicy=v6-upright&imwidth=270",
        filename: "prod-1.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image2",
        width: 1080,
        height: 650,
        url: "https://content.rolex.com/dam/2022-11/upright-bba-with-shadow/m124060-0001.png?impolicy=v6-upright&imwidth=270",
        filename: "prod-2.png",
        size: 1080,
        type: "image/png",
      },
      {
        id: "image3",
        width: 1080,
        height: 650,
        url: "https://images.pexels.com/photos/1697214/pexels-photo-1697214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        filename: "prod-3.png",
        size: 1080,
        type: "image/png",
      },
    ],
  },
];

module.exports = products;
